spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        format_sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:3306/cement
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB