spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        format_sql: true
  datasource:
    url: jdbc:mysql://192.168.0.80:3306/cement
    username: root
    password: Skdlxmfhem3323!


  mail:
    host: smtp.gmail.com
    port: 587
    username: cement.apply@gmail.com
    password: gswwqnjgnqzlhdid
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB