name: Back CI/CD

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test

      - name: SpringBoot Server Start
        run: nohup java –jar ./build/libs/cement-0.0.1-SNAPSHOT.jar &