name: Back CI/CD

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Stop old server (ignore error)
        run: |
          killall -9 java || true

      - name: Remove old server in ~/soruce (ignore error)
        run: |
          rm -rf ~/source || true

      - name: Copy new server to ~/soruce
        run: |
          mkdir -p ~/source
          cp -R ./ ~/source

      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test

      - name: Run new server (in background)
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          cd ~/source
          nohup java –jar ./build/libs/cement-0.0.1-SNAPSHOT.jar &